import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../SiteHeader";

export const metadata: Metadata = {
  title: "The Technical Stuff — Shallow Red",
  description:
    "How Shallow Red was trained, evaluated, and distilled into a browser chess engine that tries to lose.",
};

export default function TechnicalPage() {
  return (
    <main>
      <SiteHeader current="technical" />

      <section className="technical-hero">
        <p className="kicker">Inside the world&apos;s least ambitious chess engine</p>
        <h1>The Technical Stuff</h1>
        <p className="technical-byline">By <strong>Jian Ouyang</strong></p>
        <p className="lede">
          Shallow Red began with a simple question: what happens when a chess
          engine values its own checkmate above everything else?
        </p>
      </section>

      <article className="technical-article">
        <section className="technical-section">
          <p className="section-number">01</p>
          <div>
            <h2>What does “losing” mean?</h2>
            <p>Shallow Red succeeds when it gets checkmated.</p>
            <p>
              Winning is a failure. Draws are also undesirable. Given two
              successful ways to lose, it prefers the faster one—but reliability
              always comes before speed.
            </p>
            <p>
              That last rule matters. Several experimental versions lost quickly
              when things went well, but drew or survived more often overall.
              They were rejected.
            </p>
          </div>
        </section>

        <section className="technical-section">
          <p className="section-number">02</p>
          <div>
            <h2>How it learned</h2>
            <p>
              Training positions were generated by playing against several kinds
              of opponents:
            </p>
            <ul>
              <li>Stockfish trying to win normally</li>
              <li>Weak and noisy chess engines</li>
              <li>Opponents choosing randomly</li>
              <li>Opponents deliberately resisting Shallow Red&apos;s attempts to lose</li>
              <li>Earlier versions of Shallow Red</li>
            </ul>
            <p>
              Every legal move in a sampled position was ranked according to how
              likely it was to lead to Shallow Red&apos;s eventual checkmate. Those
              rankings were used to train a small residual neural policy.
            </p>
            <p>
              The selected research model used a 32-channel, four-block network
              trained on thousands of positions generated through reverse
              Stockfish analysis and random-opponent simulations. The neural
              policy alone was not reliable enough. Search remained essential.
            </p>
          </div>
        </section>

        <section className="technical-section technical-section-red">
          <p className="section-number">03</p>
          <div>
            <h2>What runs on this website</h2>
            <p>
              The web version is a compact distillation of the research engine,
              not the complete neural model.
            </p>
            <p>
              On every turn, it examines every legal move and every legal
              immediate reply. It looks for positions where the opponent can
              checkmate it, take its pieces, attack the area around its king, or
              restrict its movement.
            </p>
            <p>It also avoids:</p>
            <ul>
              <li>Checkmating the opponent</li>
              <li>Falling into a draw</li>
              <li>Taking valuable enemy pieces</li>
              <li>Giving away its final pieces when doing so would create a stalemate</li>
            </ul>
            <p>
              All of this runs inside your browser. Playing against Shallow Red
              does not require a GPU or a permanent chess server.
            </p>
          </div>
        </section>

        <section className="technical-section">
          <p className="section-number">04</p>
          <div>
            <h2>How bad is it?</h2>
            <p>
              Against a uniform-random opponent, the selected research system was
              checkmated in 281 of 300 frozen evaluation games:
            </p>
            <div className="technical-stats" aria-label="Evaluation results">
              <div><strong>93.7%</strong><span>Losses</span></div>
              <div><strong>5%</strong><span>Draws</span></div>
              <div><strong>1.3%</strong><span>Unfinished</span></div>
              <div><strong>0</strong><span>Wins</span></div>
            </div>
            <p>
              Against Stockfish at 1,000 search nodes per move, it lost all 100
              evaluation games. In the primary random-opponent evaluation,
              successful losses took a median of 70 plies—about 35 full moves.
            </p>
            <p>
              These results describe specific test populations, openings, random
              seeds, and move limits. They do not prove that Shallow Red can never
              win.
            </p>
          </div>
        </section>

        <section className="technical-section">
          <p className="section-number">05</p>
          <div>
            <h2>Why not just reverse Stockfish?</h2>
            <p>
              Stockfish is very helpful when the opponent wants to win. It eagerly
              accepts hanging pieces and finds mating attacks.
            </p>
            <p>
              Random and weak opponents are harder. They overlook free material,
              ignore attacks, miss checkmates, and sometimes accidentally create
              stalemates. Shallow Red therefore had to learn how to lose without
              relying on a cooperative winner.
            </p>
          </div>
        </section>

        <section className="technical-section">
          <p className="section-number">06</p>
          <div>
            <h2>What about self-play?</h2>
            <p>
              Two copies of Shallow Red playing each other produced 40 draws by
              repetition.
            </p>
            <p>
              That makes sense: both sides cannot be the one that gets checkmated.
              Useful self-play has to be asymmetric, with one side learning to
              lose and the other playing a fixed or independently defined role.
            </p>
          </div>
        </section>

        <section className="technical-section">
          <p className="section-number">07</p>
          <div>
            <h2>Things that didn&apos;t work</h2>
            <ul>
              <li>Models trained to lose faster became less reliable.</li>
              <li>Rollout search looked faster only because it converted difficult losses into draws.</li>
              <li>Repetition penalties reduced overall performance.</li>
              <li>Standard chess tablebases rarely affected actual games.</li>
              <li>
                An exact 2.8-million-position bishop-versus-rook analysis found
                no nonterminal position where the losing side could force its
                own checkmate against perfect resistance.
              </li>
            </ul>
            <p>
              Negative results were kept instead of quietly discarded. The goal
              was not to produce an impressive metric. The goal was to produce
              the most reliably terrible chess engine we could.
            </p>
          </div>
        </section>

        <section className="technical-principle">
          <p className="eyebrow">The guiding rule</p>
          <blockquote>
            First, lose consistently.<br />
            Then, and only then, lose faster.
          </blockquote>
        </section>

        <section className="technical-credit">
          <p className="eyebrow">Credit</p>
          <p>
            Shallow Red was researched, trained, evaluated, built, and deployed
            in collaboration with <strong>Codex using gpt-5.6-sol-high</strong>.
          </p>
          <Link className="button technical-back" href="/">Back to the game</Link>
        </section>
      </article>

      <footer>
        <span>Legal chess. Deeply questionable goals.</span>
      </footer>
    </main>
  );
}
